#include "repository_generator.hpp"

#include <chrono>
#include <format>
#include <fstream>
#include <system_error>

#include "uuid.hpp"

namespace oep::cli::generator {

namespace {

constexpr const char* kOepVersion = "0.1.0";
constexpr const char* kTemplateVersion = "1.0";

std::string current_timestamp_iso8601() {
    const auto now = std::chrono::system_clock::now();
    return std::format("{:%Y-%m-%dT%H:%M:%SZ}", std::chrono::floor<std::chrono::seconds>(now));
}

void write_file(const std::filesystem::path& path, const std::string& contents) {
    std::ofstream file(path, std::ios::binary);
    file << contents;
}

} // namespace

GenerationResult generate_foundation_repository(const std::filesystem::path& destination,
                                                 const std::string& repository_name) {
    std::error_code error_code;

    if (std::filesystem::exists(destination, error_code) &&
        !std::filesystem::is_empty(destination, error_code)) {
        return {false, "destination '" + destination.string() + "' already exists and is not empty"};
    }

    static constexpr const char* kSubdirectories[] = {
        "repository", "workspace", "packages", "cache", "logs", "exports", "settings"};

    for (const char* subdirectory : kSubdirectories) {
        std::filesystem::create_directories(destination / subdirectory, error_code);
        if (error_code) {
            return {false, "failed to create '" + std::string(subdirectory) + "': " + error_code.message()};
        }
    }

    const std::string repository_id = generate_uuid_v4();
    const std::string creation_date = current_timestamp_iso8601();

    write_file(destination / "README.md",
               "# " + repository_name + "\n\nAn Open Engineering Platform (OEP) repository.\n");

    write_file(destination / ".gitignore",
               "# Generated by OEP Foundation\n\ncache/\nlogs/\nexports/\n");

    write_file(destination / "repository.json",
               "{\n"
               "  \"repositoryId\": \"" + repository_id + "\",\n"
               "  \"oepVersion\": \"" + kOepVersion + "\",\n"
               "  \"templateVersion\": \"" + kTemplateVersion + "\",\n"
               "  \"creationDate\": \"" + creation_date + "\"\n"
               "}\n");

    write_file(destination / "workspace.json",
               "{\n"
               "  \"defaultStudio\": null,\n"
               "  \"theme\": \"default\",\n"
               "  \"workspaceVersion\": \"" + std::string(kTemplateVersion) + "\"\n"
               "}\n");

    return {true, "created repository '" + repository_name + "' at " + destination.string()};
}

} // namespace oep::cli::generator
